mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:Mapper/*.xml
server:
  port: 8080
jwt:
  alg: "RS256"
  typ: "JWT"
  access_token_expiration: 300
  refresh_token_expiration: 3000
  issuer: "alivia"
  aduience: "resource"

keyPair:
  alg: "RSA"
  size: 2048



secret:
  access_pvt: "private.key"
  access_pub: "public.key"
  refresh_pvt: ""
  refresh_pub: ""
spring:
  profiles:
    active: docker
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}}/${DB_NAME}}?useSSL=false
    #url: jdbc:mysql://localhost:3306/JWT
    username: ${DB_USERNAME}}
    #password: Jsq925522
    password: ${DB_PASSWORD}
  mail:
    host: smtp.qq.com
    port: 587
    username: 834622793@qq.com
    password: dejrpnvugdrdbdij
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true



message.mail.verification:
  Thank you for creating an account. Please click the link below to activate your account. This link will expire in 1 hours.
message.mail.expiration: 3600
