
server:
  port: 8080
jwt:
  alg: "RS256"
  typ: "JWT"
  access_token_expiration: 300
  refresh_token_expiration: 3000
  issuer: "alivia"
  audience: "resource"

keyPair:
  alg: "RSA"
  size: 2048

aws:
  accessKeyID: AKIAY25PJ3QHYS3TUUFN
  secretKey: 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



secret:
  access_pvt: access_private_key.pem
  access_pub: access_public_key.pem
  refresh_pvt: refresh_private_key.pem
  refresh_pub: refresh_public_key.pem

puk:
  access_token.bucket: rsasecrets
  access_token.key: access_public_key.pem
  refresh_token.bucket: rsasecrets
  refresh_token.key: refresh_public_key.pem

pvt:
  access_token.bucket: rsasecrets
  access_token.key: access_private_key.pem
  refresh_token.bucket: rsasecrets
  refresh_token.key: refresh_private_key.pem

spring:
  jpa:
    properties.hibernate.hbm2ddl.auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate.naming-strategy.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  profiles:
    active: docker
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://mysql/JWT?useSSL=false
    url: jdbc:mysql://localhost:3306/JWT
    username: root
    password: Jsq925522
    #password: root
  mail:
    host: smtp.qq.com
    port: 587
    username: 834622793@qq.com
    password: dejrpnvugdrdbdij
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true

  redis:
    host: 127.0.0.1
    port: 6379
  #连接池最大链接数默认值为8
    lettuce.pool.max-active: 8
  #连接池最大阻塞时间（使用负值表示没有限制）默认为-1
    lettuce.pool.max-wait: -1
  #连接池中的最大空闲连接数 默认为8
    lettuce.pool.max-idle: 8
  #连接池中的最小空闲连接数 默认为8
    lettuce.pool.min-idle: 0






message.mail.verification:
  Thank you for creating an account. Please click the link below to activate your account. This link will expire in 1 hours.
message.mail.expiration: 3600
