mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:Mapper/*.xml
server:
  port: 8080
jwt:
  alg: "RS256"
  typ: "JWT"
  access_token_expiration: 300
  refresh_token_expiration: 3000
  issuer: "alivia"
  aduience: "resource"

keyPair:
  alg: "RSA"
  size: 2048



secret:
  pvt: "private.key"
  pub: "public.key"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JWT?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Jsq925522
  mail:
    host: smtp.qq.com
    port: 587
    username: 834622793@qq.com
    password: dejrpnvugdrdbdij
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true



message.mail.verification:
  Thank you for creating an account. Please click the link below to activate your account. This link will expire in 24 hours.
